project:
  type: book

book:
  title: "Le livre de Judith"
  author: "Judith Bourque"
  date: "7/11/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

